### ISSUE TITLE
Website Proposal: Docusaurus

### ISSUE THREAD

**Issue by bravo-kernel** [pester/pester.github.com#8]
Since there are a lot of [suggestions for the new website technology](https://github.com/pester/pester.github.com/issues/7)  it might be a good idea to compare them using a feature-list for a clean and objective comparison. 

Features below were copied directly from [Docusaurus v2](https://v2.docusaurus.io/), as a starting point for the discussion:

- [ ] markdown documentation for "regular" docs
- [ ] auto-generated API/Dev pages using the `Get-Help` found in module(s)
- [ ] fully theme'able
- [ ] localization-ready
- [ ] versioning
- [ ] fully indexed search (free, e.g. Free Algolia Search)
- [ ] website-previews (for all new PRs, as e.g. handled by Netlify, using github hook)
- [ ] zero-touch website-deployments (as also handled by e.g. Netlify)

Additional (biased) Docusaurus info:

- all pages also support React so **anything** could be added to recreate e.g. the index used by [dbatools.io](https://dbatools.io/)
- all maintenance would be the responsibility of the React community 
- modern, SPA, large community

## Questions: 

- [X] **answered:** separate docs into an isolated repo ~OR add to the existing repo as e.g. `website` subdir~
- [X] **answered:** if separated, can we be 100% sure that the latest `Get-Help` is generated (after changes in the code repo)? `webhook trigger from the code repo to the website repo`
- [X] **answered:** there is talk about two solutions, e.g. Docu and Jekyll. What's the reasoning behind that? `No longer applicable, should be a single solution`

## How would this be implemented?

- [ ] fill repo with intitial docusaurus
- [ ] configure docusaurus
- [ ] configure Docusaurus.Powershell + document
- [ ] setup netlify basics (point to master, etc): `pester.netlify.com`
- [ ] point `pester.dev` to `pester.netlify.com`
- [ ] let netlify handle SSL (letsencrypt, free)
- [ ] setup ci/cd
- [ ] setup webhook from code repo to trigger this repo (to render latest Get-Help)

After that, get help updating the theme as required.

**Comment by bravo-kernel** [comment]
> Instead of reinventing the wheel and failing in an area where Powershell does not excel (frontend development), this project provides a bridge between your Powershell Comment-Based Help and Docusaurus v2, a static website generator written in React, with an empahasis on ease-of-use.

> This cross-technology approach allows you to focus on documenting your modules without having to worry about frontend development and maintenance, all handled by the Docusaurus community.

**Comment by scrthq** [comment]
FWIW, both VaporShell (Jekyll) and PSGSuite (MkDocs) have site content generated from comment-based help. Definitely interested in Docusaurus as a new tool, but supportability may be lacking due to limited familiarity with customization across the contributors for this effort.

**Comment by nohwnd** [comment]
Okay I see that Docusaurus works a bit differently than I thought, what I thought it does is just take the help in some form and generates html from it, but it is a lot more. I think customizing a React app would be more difficult than using Jekyll. Can we maybe use Jekyll for everything except help, and use different subdomain for help via docusaurus? That way we don't have to decide now, and we can just try it 🙂

**Comment by bravo-kernel** [comment]
@nohwnd docusaurus takes the `Get-Help` and transforms it into **markdown** pages per cmdlet/function (like this example [here](https://github.com/alt3/Docusaurus.Powershell/blob/master/docusaurus/docs/CmdLets/New-DocusaurusHelp.mdx)). Plain pages are just static markdown.

**Good to know:** `Edit this page` for the `Get-Help` markdown pages would point to the Powershell source-file containing the Get-Help and not the markdown document that was generated for it.

@scrthq React is the largest frontend community out there, I don't see that 💡

**Comment by vexx32** [comment]
FWIW for cmdlet documentation we could literally just use PlatyPS to generate Markdown and then have another layer that adds the couple extra bits and bobs required by Jekyll to generate a page.

Not sure how that compares to working directly with the Get-Help output (which is essentially in plaintext) but I'm sure the difference isn't huge. If docosaurus can do it in one step rather than two, that's probably a simpler solution to go with.

**Comment by bravo-kernel** [comment]
@vexx32 docusaurus also uses PlatyPS so that's no difference. Also, to prevent misunderstandings, even though I think it makes sense to onboard/invest in new(er) technologies it's really equal to me which solution will be chosen. Whatever suits this group best should do it, it was only a suggestion.

I do hope the feature list will be taken into consideration. Open minded ftw.

**Comment by bravo-kernel** [comment]
https://v2.docusaurus.io/showcase shows various theming examples in the wild. Could help to give an impression of what is possible.

**Comment by bravo-kernel** [comment]
Closing as a PR is now open to implement this.

https://github.com/pester/docs/pull/1

**Comment by bravo-kernel** [comment]
Closing as a PR is now open to implement this at https://github.com/pester/docs/pull/1
